name: Create Tags

on:
  push:
    paths:
    - 'src/tags/*'
    - 'bin/createtags.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        ref: main
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"
    - name: Create tags.json
      run: |
        python bin/createtags.py src/tags/* > var/tags.json
    - name: Push update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./bin/update.sh
